--- #YAML:1.0
name:               Net-Tor-Servers
version:            0.02
abstract:           Perl extension to query a Tor Directory and collect information on servers
author:
    - Andy Dixon <andy@apple.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
